language: csharp
solution: AnonymousIncomeComparisonTool.sln
 
install:
  - sudo apt-get install nunit-console
  - nuget restore AnonymousIncomeComparisonTool.sln
 
script:
  - xbuild AnonymousIncomeComparisonTool.sln
  - nunit-console AnonymousIncomeComparisonTool.Tests/bin/Debug/AnonymousIncomeComparisonTool.Tests.dll